### ISSUE TITLE
Problème de concurrence entre deux adresses de notre site Web sur les moteurs de recherches (www versus non-www)

### ISSUE THREAD

**Issue by spmarion** [scenarex/scenarex.ca#1]
www vs non-www
•	En ce moment, le site affiche les deux versions du site Web sur les moteurs. Pour éviter de créer des contenus dupliqués, il serait important de créer une redirection dans le fichier HTaccess afin de rediriger le trafic vers la version retenue.
•	Pour ajouter la règle dans le HTaccess : https://www.inmotionhosting.com/support/website/htaccess/force-www-htaccess
•	Il faudra ensuite préciser la version « favorite » dans la Search Console de Google : https://support.google.com/webmasters/answer/44231?hl=fr

**Comment by stevebreault** [comment]
Problem was related to the auto-update of the nginx configuration files.
